POST {{baseurl}}/api/chat
content-type: application/json

{
"question": "Whats your  name?"
}

> {%
    client.test("Check if the response is correct", function() {
        responseBody = JSON.stringify(response.body);
        client.assert(responseBody.toLowerCase().includes("large language model".toLowerCase()));
    });
%}

###

POST {{baseurl}}/api/chat
content-type: application/json

{
  "question": "write a short story in simple words about freedom"
}

###

POST {{baseurl}}/api/chat
content-type: application/json

{
  "question": "can you do a recursion for the same?"
}


###

POST {{baseurl}}/api/chat
content-type: application/json

{
  "question": "what is my last question"
}