

### Search by department
POST {{baseurl}}/api/internaldata/chat
Content-Type: application/json

{
  "question":"How is the revenue situation for the company?",
  "department": "Executive Management"
}

### Search by department without department
POST {{baseurl}}/api/internaldata/chat
Content-Type: application/json

{
  "question":"How is the revenue situation for the company?"

}


###

# curl -X 'POST'
#  'http://localhost:8080/api/internal/agent/upload'
#  -H 'accept: */*'
#  -H 'Content-Type: multipart/form-data'
#  -F 'file=@policy.docx;type=application/vnd.openxmlformats-officedocument.wordprocessingml.document'
POST http://localhost:8080/api/internal/agent/upload
accept: */*
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="policy.docx"

< policy.docx
--WebAppBoundary--

###

