

### Create Multiple Documents


POST {{baseurl}}/api/vectordb/documents
Content-Type: application/json

[
  {
    "content": "Our e-commerce platform's backend is built with Spring Boot, utilizing Spring Security for authentication and Spring Data JPA for database operations",
    "department": "IT"
  },
  {
    "content": "The company's board of directors is led by Jane Smith, a seasoned e-commerce executive with 20 years of industry experience",
    "department": "Executive Management"
  },
  {
    "content": "Our customer-facing web application is developed using React, providing a responsive and interactive shopping experience",
    "department": "IT"
  },
  {
    "content": "Last quarter's revenue reached $24.7 million, marking a 15% year-over-year growth",
    "department": "Executive Management"
  },
  {
    "content": "Employee attendance last month averaged 94%, with our flexible work-from-home policy contributing to high engagement",
    "department": "HR"
  },
  {
    "content": "We leverage machine learning for personalized product recommendations, implemented using TensorFlow and Python",
    "department": "IT"
  },
  {
    "content": "Our mobile app, available on both iOS and Android platforms, accounts for 40% of our total sales",
    "department": "IT"
  }
]


### Search Documents

POST {{baseurl}}/api/vectordb/documents/search
Content-Type: application/json

{
  "question":"How is the revenue situation for the company?",
  "department": "Executive Management"
}


### Search Documents with limit

POST {{baseurl}}/api/vectordb/documents/search
Content-Type: application/json

{
  "question":"How is your platform built on?",
  "department": "IT",
  "limit": 2
}

### Search Documents with limit and distance

POST {{baseurl}}/api/vectordb/documents/search
Content-Type: application/json

{
  "question": "How is your platform built on?",
  "department": "IT",
  "limit": 2,
  "maximumDistance": 0.538
}