
### contains Upright Vacuum
POST {{baseurl}}/api/unstructured-data/chat-with-text-and-image
content-type: application/json

{
  "question": "What are the types of vaccum cleaners?"
}

> {%
    client.test("Check if the response contains Upright Vacuum", function() {

        responseBody = JSON.stringify(response.body);

        client.assert(responseBody.toLowerCase().includes("Upright Vacuum".toLowerCase()));
    });
%}

### contains PG Electronics
POST {{baseurl}}/api/unstructured-data/chat-with-text-and-image
content-type: application/json

{
  "question": "Who gives discount for vaccum cleaners?"
}

> {%
    client.test("Check if the response contains PG Electronics", function() {

        responseBody = JSON.stringify(response.body);

        client.assert(responseBody.toLowerCase().includes("PG Electronics".toLowerCase()));
    });
%}


### What are the colors used
POST {{baseurl}}/api/unstructured-data/chat-with-text-and-image
content-type: application/json

{
  "question": "What are the colors used in image?"
}

> {%
    client.test("Check if the response contains red", function() {
        responseBody = JSON.stringify(response.body);
        client.assert(responseBody.toLowerCase().includes("red".toLowerCase()));
    });
%}

### What are the objects in the image?
POST {{baseurl}}/api/unstructured-data/chat-with-text-and-image
content-type: application/json

{
  "question": "What are the Objects in image?"
}

> {%
    client.test("Check if the response contains coupon", function() {
        responseBody = JSON.stringify(response.body);
        client.assert(responseBody.toLowerCase().includes("coupon".toLowerCase()));
    });
%}