
### Insert single document
POST {{baseurl}}/api/vectordb/document
content-type: application/json

{
  "content": "Our e-commerce platform's backend is built with Spring Boot, utilizing Spring Security for authentication and Spring Data JPA for database operations "
}

> {%
    client.test("Check if the response contains Valid Data", function() {

        responseBody = JSON.stringify(response.body);

        const hasData = responseBody.toLowerCase().includes("Our e-commerce".toLowerCase())


        client.assert(hasData);
    });
%}


### Create Multiple Documents


POST {{baseurl}}/api/vectordb/documents
Content-Type: application/json

[
  {    "content": "The company's board of directors is led by Jane Smith, a seasoned e-commerce executive with 20 years of industry experience"  },

  {    "content": "Our customer-facing web application is developed using React, providing a responsive and interactive shopping experience"  },

  {    "content": "Last quarter's revenue reached $24.7 million, marking a 15% year-over-year growth"  },

  {    "content": "Employee attendance last month averaged 94%, with our flexible work-from-home policy contributing to high engagement"  },

  {    "content": "We leverage machine learning for personalized product recommendations, implemented using TensorFlow and Python"  },

  {    "content": "Our mobile app, available on both iOS and Android platforms, accounts for 40% of our total sales"  }

]
