
### What is happening
POST {{baseurl}}/api/unstructured-data/chat-with-video
content-type: application/json

{
  "question": "What is this video about?"
}

> {%
    client.test("Check if the response contains QuickSweep Slim", function() {

        responseBody = JSON.stringify(response.body);

        const hasThree = responseBody.toLowerCase().includes("QuickSweep Slim".toLowerCase())


        client.assert(hasThree);
    });
%}

### How much it cost
POST {{baseurl}}/api/unstructured-data/chat-with-video
content-type: application/json

{
  "question": "How much it cost?"
}

> {%
    client.test("Check if the response contains the 99", function() {
        responseBody = JSON.stringify(response.body);
        client.assert(responseBody.toLowerCase().includes("99".toLowerCase()));
    });
%}

### Who sells it
POST {{baseurl}}/api/unstructured-data/chat-with-video
content-type: application/json

{
  "question": "Who sells it?"
}

> {%
    client.test("Check if the response has PG", function() {
        responseBody = JSON.stringify(response.body);
        client.assert(responseBody.toLowerCase().includes("PG".toLowerCase()));
    });
%}

