
##- What is happening
#- What are the food arrangements
#- Where is the location

### What is happening
POST {{baseurl}}/api/unstructured-data/chat-with-image
content-type: application/json

{
  "question": "How many coupons are there?"
}

> {%
    client.test("Check if the response contains 3", function() {

        responseBody = JSON.stringify(response.body);

        const hasThree = responseBody.toLowerCase().includes("3".toLowerCase()) || responseBody.toLowerCase().includes("three".toLowerCase())


        client.assert(hasThree);
    });
%}

### is there any discounts car wash
POST {{baseurl}}/api/unstructured-data/chat-with-image
content-type: application/json

{
  "question": "is there any discounts car wash?"
}

> {%
    client.test("Check if the response contains the 25", function() {
        responseBody = JSON.stringify(response.body);
        client.assert(responseBody.toLowerCase().includes("25".toLowerCase()));
    });
%}

### Which company provides discount for gym
POST {{baseurl}}/api/unstructured-data/chat-with-image
content-type: application/json

{
  "question": "Which company provides discount for gym?"
}

> {%
    client.test("Check if the response has 50", function() {
        responseBody = JSON.stringify(response.body);
        client.assert(responseBody.toLowerCase().includes("50".toLowerCase()));
    });
%}

### What are the colors used
POST {{baseurl}}/api/unstructured-data/chat-with-image
content-type: application/json

{
  "question": "What are the colors used?"
}

> {%
    client.test("Check if the response contains red", function() {
        responseBody = JSON.stringify(response.body);
        client.assert(responseBody.toLowerCase().includes("red".toLowerCase()));
    });
%}

### What are the Objects in Image
POST {{baseurl}}/api/unstructured-data/chat-with-image
content-type: application/json

{
  "question": "What are the Objects in Image ?"
}

> {%
    client.test("Check if the response contains vacuum cleaner", function() {
        responseBody = JSON.stringify(response.body);
        client.assert(responseBody.toLowerCase().includes("vacuum cleaner".toLowerCase()));
    });
%}
