
### What is happening
POST {{baseurl}}/api/unstructured-data/chat-with-audio
content-type: application/json

{
  "question": "What is this audio about?"
}

> {%
    client.test("Check if the response contains customer service", function() {

        responseBody = JSON.stringify(response.body);

        const hasThree = responseBody.toLowerCase().includes("customer service".toLowerCase())


        client.assert(hasThree);
    });
%}

### Who are the persons involved and whats their name
POST {{baseurl}}/api/unstructured-data/chat-with-audio
content-type: application/json

{
  "question": "Who are the persons involved and whats their name?"
}

> {%
    client.test("Check if the response contains the Sarah", function() {
        responseBody = JSON.stringify(response.body);
        client.assert(responseBody.toLowerCase().includes("Sarah".toLowerCase()));
    });
%}

### Has the problem been solved
POST {{baseurl}}/api/unstructured-data/chat-with-audio
content-type: application/json

{
  "question": "Has the problem been solved , say yes or no?"
}

> {%
    client.test("Check if the response has PG", function() {
        responseBody = JSON.stringify(response.body);
        client.assert(responseBody.toLowerCase().includes("No".toLowerCase()));
    });
%}

